### create-user
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Jurjen",
  "email": "jurjen@vorhauer.nl",
  "password": "Welkom123!",
  "born": "1967-04-01"
}

### get-jurjen
GET http://localhost:8080/users/9ee43b12-dc09-4788-b0f3-d4359152f474

### get-all-users
GET http://localhost:8080/users

### login-jurjen
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "jurjen@vorhauer.nl",
  "password": "Welkom123!"
}

### invalid-name-and-password
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "welkom123",
  "email": "weet@niet.het",
  "password": "welkom0123!",
  "born": "2001-11-09"
}

### invalid-email
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Tester",
  "email": "weet-niet.het",
  "password": "Welkom0123!",
  "born": "2001-11-09"
}


### create-temp-user
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "The Temp",
  "email": "temp@test.er",
  "password": "Welkom123!",
  "born": "2001-11-09"
}

### get-temp-user
GET http://localhost:8080/users/1fea6d11-262e-4a17-967d-4cfe6e5e945b

### delete-temp-user
DELETE http://localhost:8080/users
Content-Type: application/json

{
  "email": "temp@test.er"
}


### get-info
GET http://localhost:8080/info
