### create-user
POST {{ host }}/users
Content-Type: application/json

{
  "name": "Jurjen",
  "email": "jurjen@vorhauer.nl",
  "password": "Welkom123!",
  "born": "1967-04-01"
}

### get-all-users
GET {{ host }}/users

### get-jurjen
GET {{ host }}/users/01GNVWJKZ2HV0KNCWEEXHARDQC

### get-me
GET {{ host }}/users/me
Authorization: Bearer {{ authorized }}


### login-jurjen
POST {{ host }}/users/login
Content-Type: application/json

{"email": "jurjen@vorhauer.nl", "password": "Welkom123!"}

> {% client.global.set("authorized", response.body.access_token); %}

### post-task
POST {{ host }}/tasks
Content-Type: application/json
Authorization: Bearer {{ authorized }}

{
  "title": "test with html encoding",
  "body": "Encoded <script> tags should not allow <h1>crap</h1>",
  "due": "2023-04-01T10:00:00",
  "status": "Blank"
}

### post-bookmark
POST {{ host }}/bookmarks
Content-Type: application/json
Authorization: Bearer {{ authorized }}

{
  "url": "http://localhost:8080/users",
  "title": "test with html encoding",
  "body": "Encoded <script> tags should not allow <h1>crap</h1>"
}

### invalid-name-and-password
POST {{ host }}/users
Content-Type: application/json

{
  "name": "welkom123",
  "email": "weet@niet.het",
  "password": "welkom0123!",
  "born": "2001-11-09"
}

### invalid-email
POST {{ host }}/users
Content-Type: application/json

{
  "name": "Tester",
  "email": "weet-niet.het",
  "password": "Welkom0123!",
  "born": "2001-11-09"
}


### create-temp-user
POST {{ host }}/users
Content-Type: application/json

{
  "name": "The Temp",
  "email": "temp@test.er",
  "password": "Welkom123!",
  "born": "2001-11-09"
}

### get-temp-user
GET {{ host }}/users/01GW28MS05S3M5XSV5NYADRCPA

### delete-temp-user
DELETE {{ host }}/users
Content-Type: application/json

{
  "email": "temp@test.er"
}


### get-info
GET {{host}}/info
