### create-user
POST {{ host }}/users
Content-Type: application/json

{
  "name": "Jurjen",
  "email": "jurjen@vorhauer.nl",
  "password": "Welkom123!",
  "born": "1967-04-01"
}

### get-all-users
GET {{ host }}/users

### get-jurjen
GET {{ host }}/users/01H8H8MS1ZGQYGJDH1W5ZZBGRR

### get-me
GET {{ host }}/users/me
Authorization: Bearer {{ authorized }}


### login-jurjen
POST {{ host }}/users/login
Content-Type: application/json

{"email": "jurjen@vorhauer.nl", "password": "Welkom123!"}

> {% client.global.set("authorized", response.body.access_token); %}

### post-note
POST {{ host }}/notes
Content-Type: application/json
Authorization: Bearer {{ authorized }}

{
  "title": "test with <html> encoding",
  "body": "Just a very nice story about incremental development and having fun while doing so",
  "due": "2024-09-01T10:00:00",
  "status": "ToDo",
  "access": "Private"
}

### invalid-name-and-password
POST {{ host }}/users
Content-Type: application/json

{
  "name": "welkom123",
  "email": "weet@niet.het",
  "password": "welkom0123!",
  "born": "2001-11-09"
}

### invalid-email
POST {{ host }}/users
Content-Type: application/json

{
  "name": "Tester",
  "email": "weet-niet.het",
  "password": "Welkom0123!",
  "born": "2001-11-09"
}

### create-temp-user
POST {{ host }}/users
Content-Type: application/json

{
  "name": "The Temp",
  "email": "temp@test.er",
  "password": "Welkom123!",
  "born": "2001-11-09",
  "bio": "bio test maar wel met <h1>HALLO</h1> html tags erin"
}

### get-temp-user
GET {{ host }}/users/01H784QDS73R667E3WQH9TS4B1

### delete-temp-user
DELETE {{ host }}/users
Content-Type: application/json

{
  "email": "temp@test.er"
}


### get-info
GET {{host}}/info


### get my notes
GET {{ host }}/notes/mine
Authorization: Bearer {{ authorized }}


### Update a note
PUT {{ host }}/notes
Authorization: Bearer {{ authorized }}
Content-Type: application/json

{
  "id": "01H7TA087A8RXJ1W6VYTBJGQWG",
  "owner": "01H7T8YXEVJ0PXWAVMVJH1664Y",
  "title": "updated with an <H1>html</H1> tag",
  "body": "much shorter body <<h2> test </h2>",
  "due": "2023-10-09T12:01:32",
  "status": "Doing",
  "access": "Public"
}


### update-me
PUT {{ host }}/users
Authorization: Bearer {{ authorized }}
Content-Type: application/json

{
  "id": "01H7T8YXEVJ0PXWAVMVJH1664Y",
  "name": "Henkie",
  "password": "EvenHelem@@lAnders!5",
  "born": "1967-05-02",
  "bio": "Master of Dsiguise"
}

### restore-me
PUT {{ host }}/users
Authorization: Bearer {{ authorized }}
Content-Type: application/json

{
  "id": "01H7T8YXEVJ0PXWAVMVJH1664Y",
  "name": "Jurjen",
  "password": "Welkom123!",
  "born": "1967-04-01",
  "bio": "Master of Disguise"
}


### perform-check
GET {{ host }}/check
