### create-user
POST {{ host }}/users
Content-Type: application/json

{
  "name": "Jurjen",
  "email": "jurjen@vorhauer.nl",
  "password": "Welkom123!",
  "born": "1967-04-01"
}

### get-all-users
GET {{ host }}/users

### get-jurjen
GET {{ host }}/users/01GNVWJKZ2HV0KNCWEEXHARDQC

### login-jurjen
POST {{ host }}/users/login
Content-Type: application/json

{
  "email": "jurjen@vorhauer.nl",
  "password": "Welkom123!"
}

> {% client.global.set("authorized", response.body.access_token); %}

### post-entry-for-jurjen
POST {{ host }}/entries
Content-Type: application/json
Authorization: Bearer {{ authorized }}

{
  "title": "Deployed and Running on k8s",
  "body": "This completes the MVP, version 1.0.2. Now on to version 2 with the complete functionality as required by me",
  "status": "Blank"
}

### invalid-name-and-password
POST {{ host }}/users
Content-Type: application/json

{
  "name": "welkom123",
  "email": "weet@niet.het",
  "password": "welkom0123!",
  "born": "2001-11-09"
}

### invalid-email
POST {{ host }}/users
Content-Type: application/json

{
  "name": "Tester",
  "email": "weet-niet.het",
  "password": "Welkom0123!",
  "born": "2001-11-09"
}


### create-temp-user
POST {{ host }}/users
Content-Type: application/json

{
  "name": "The Temp",
  "email": "temp@test.er",
  "password": "Welkom123!",
  "born": "2001-11-09"
}

### get-temp-user
GET {{ host }}/users/01GSFXYNST540H44H170JQNQJB

### delete-temp-user
DELETE {{ host }}/users
Content-Type: application/json

{
  "email": "temp@test.er"
}


### get-info
GET {{ host }}/info
