addSbtPlugin("com.github.sbt"   % "sbt-release"         % "1.1.0")
addSbtPlugin("ch.epfl.scala"    % "sbt-version-policy"  % "2.1.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"         % "0.6.4")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"        % "0.10.4")
addSbtPlugin("de.gccc.sbt"      % "sbt-jib"             % "1.3.4")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"       % "1.6.1")
