name: test with coverage
on:
  push:
    paths-ignore:
      - '**.md'
      - 'k8s/**.yaml'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'k8s/**.yaml'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true
          cache: 'sbt'
      - name: Tests
        run: sbt -Dsbt.color=false coverage test coverageReport
        env:
          ASTRA_USERNAME: ${{ secrets.ASTRA_USERNAME }}
          ASTRA_PASSWORD: ${{ secrets.ASTRA_PASSWORD }}
          ASTRA_SCB: ${{ secrets.ASTRA_SCB }}
          KAMON_TOKEN: ${{ secrets.KAMON_TOKEN }}
          HOSTNAME: 'github-runner'
      - name: Upload dependency graph
        uses: scalacenter/sbt-dependency-submission@v2
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
