name: CI
on: [push, pull_request]
permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true
          cache: 'sbt'
      - name: Tests
        run: sbt test
        env:
          ASTRA_USERNAME: ${{ secrets.ASTRA_USERNAME }}
          ASTRA_PASSWORD: ${{ secrets.ASTRA_PASSWORD }}
          ASTRA_SCB: ${{ secrets.ASTRA_SCB }}
          KAMON_TOKEN: ${{ secrets.KAMON_TOKEN }}
      - name: Upload dependency graph
        uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
